apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze_web
spec:
  selector:
    matchLabels:
      app: analyze_web
  replicas: 2
  template:
    metadata:
      labels:
        app: analyze_web
    spec:
      containers:
      - name: analyze_web
        image: hub.pingcap.net/robert/analyze-web:master
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: analyze_web
  labels:
    app: analyze_web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31112
    protocol: TCP
  selector:
    app: analyze_web