apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze-web
spec:
  selector:
    matchLabels:
      app: analyze-web
  replicas: 1
  
  template:
    metadata:
      labels:
        app: analyze-web
    spec:
      containers:
      - name: analyze-web
        image: hub.pingcap.net/robert/analyze-web:master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: analyze-web-service
  labels:
    app: analyze-web-serivce
spec:
  type: NodePort
  selector:
    app: analyze-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31112
    protocol: TCP
  